name: build-tickets-pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: cd tickets && npm install

      - name: Start application
        run: cd tickets && npm start
