name: deploy-orders

on:
  push: 
    branches:
     -  main
    paths:
      -  'orders2/**'

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
     - uses: actions/checkout@v2 
     - name: Build Docker image
       run: |
         cd tickets 
         docker build -t sydsfn/order-demo-2 .
     - name: Login to Docker Hub
       run: |
         docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
       env: 
         DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
     - uses: digitalocean/action-doctl@v2
       with:
         token: ${{secrets.DIGITAL_OCEAN_ACCESS_TOKEN}}
     - name: Digital ocean config
       run: |
         doctl kubernetes cluster kubeconfig save ticket
         kubectl rollout restart deployment ticket-depl
         
      
